const PROJECTS_DATA = [
  {
    id: "martinez-touch",
    title: "The Martinez Touch",
    tagline: "Miami Automotive Aesthetics & High-End Detailing",
    category: "automotive",
    categoryLabel: "Automotive & Detailing",
    url: "https://martinez-demo.netlify.app/",
    accent: "#FF5722",
    badge: "Miami Showcase",
    year: "2026",
    tags: ["Automotive", "Mobile Detailing", "Miami", "Booking Flow"],
    instagram: "https://www.instagram.com/themartineztouch_/",
    instagramHandle: "@themartineztouch_",
    description: "Ultra-sleek landing page and client acquisition platform for a Miami luxury automotive aesthetics studio featuring bold typography, service tier breakdowns, and client testimonials.",
    highlights: ["Interactive service calculator", "High-contrast luxury theme", "Instant quote conversion flow"]
  },
  {
    id: "andreas-details",
    title: "Andres Details",
    tagline: "Precision Auto Care & Paint Correction Specialists",
    category: "automotive",
    categoryLabel: "Automotive & Detailing",
    url: "https://andreas-details.netlify.app/",
    accent: "#3B82F6",
    badge: "Commercial Client",
    year: "2026",
    tags: ["Ceramic Coating", "Paint Correction", "Mobile Detail", "Florida"],
    instagram: "https://www.instagram.com/andresdetails/",
    instagramHandle: "@andresdetails",
    description: "Full-service automotive detailing digital presence with transparent service tiering, visual before/after showcase galleries, and optimized direct-booking CTA paths.",
    highlights: ["Transparent package comparisons", "Gallery before & after showcase", "Mobile-optimized booking"]
  },
  {
    id: "millers-detailing",
    title: "Miller's Mobile Auto Detailing",
    tagline: "Central Florida Premier Mobile Auto Care & Fleet Services",
    category: "automotive",
    categoryLabel: "Automotive & Detailing",
    url: "https://millers-detailing-demo.netlify.app/",
    accent: "#06B6D4",
    badge: "Demo Platform",
    year: "2026",
    tags: ["Mobile Detailing", "Fleet Care", "Orlando", "Kissimmee"],
    instagram: "https://www.instagram.com/staymadclean/",
    instagramHandle: "@staymadclean",
    description: "Dynamic mobile detailing portal built for local service coverage across Kissimmee and Orlando with Google review integration and instant appointment dispatching.",
    highlights: ["Localized SEO architecture", "Service area coverage maps", "Direct phone & WhatsApp integration"]
  },
  {
    id: "ceramix-auto",
    title: "Ceramix Auto Detailing",
    tagline: "Tampa Bay's Authority in Ceramic Surface Protection",
    category: "automotive",
    categoryLabel: "Automotive & Detailing",
    url: "https://ceramixauto.netlify.app/",
    accent: "#10B981",
    badge: "Elite Ceramic",
    year: "2026",
    tags: ["Ceramic Coating", "Surface Protection", "Tampa Bay", "Warranty"],
    instagram: "https://www.instagram.com/ceramixautodetailing/",
    instagramHandle: "@ceramixautodetailing",
    description: "High-end automotive protection studio website focusing on ceramic coating technology, paint protection films (PPF), and certified installer credibility.",
    highlights: ["Ceramic coating longevity guides", "Warranty registration forms", "Sleek dark glass aesthetic"]
  },
  {
    id: "royal-art-jewel",
    title: "Royal Art Jewel",
    tagline: "Haute Joaillerie & Mastercrafted Fine Diamonds",
    category: "luxury",
    categoryLabel: "Luxury & Jewelry",
    url: "https://royal-art.netlify.app/",
    accent: "#F59E0B",
    badge: "Haute Joaillerie",
    year: "2026",
    tags: ["High Jewelry", "Diamonds", "Custom Craftsmanship", "Bespoke"],
    description: "Exquisite fine jewelry flagship showcasing bespoke diamond collections, bridal artistry, and luxury custom commissions with timeless editorial aesthetics.",
    highlights: ["Editorial luxury typography", "Diamond cut showcase", "Private consultation concierge flow"]
  },
  {
    id: "chronos-watch",
    title: "CHRONOS",
    tagline: "The Authority in Time — Swiss Horology & Masterpieces",
    category: "luxury",
    categoryLabel: "Luxury & Jewelry",
    url: "https://chronos-watch-one.vercel.app/",
    accent: "#D97706",
    badge: "Vercel Featured",
    year: "2026",
    tags: ["Horology", "Swiss Movements", "Timepieces", "Luxury E-Commerce"],
    description: "Prestige watchmaking digital showcase engineered for haute horology connoisseurs, featuring caliber breakdown diagrams, titanium casing specs, and collector concierge.",
    highlights: ["Cinematic dark hero section", "Technical caliber specifications", "Interactive timepiece explorer"]
  },
  {
    id: "olympus-gym",
    title: "OLYMPUS",
    tagline: "The Elite Human Performance & Wellness Sanctuary",
    category: "fitness",
    categoryLabel: "Fitness & Wellness",
    url: "https://olympus-gym-eight.vercel.app/",
    accent: "#8B5CF6",
    badge: "Vercel Showcase",
    year: "2026",
    tags: ["Elite Gym", "Biohacking", "Recovery", "Strength Sanctuary"],
    description: "High-intensity athletic facility and recovery sanctuary website featuring biomechanical training zones, cold plunge suites, and private elite coaching rosters.",
    highlights: ["Monumental brutalist-modern layout", "Facility equipment tour", "Membership application gate"]
  },
  {
    id: "family-friends-gym",
    title: "Friendly Family Fitness",
    tagline: "Brooklyn's Premier Private Neighborhood Gym & Training",
    category: "fitness",
    categoryLabel: "Fitness & Wellness",
    url: "https://family-friends-gym.netlify.app/",
    accent: "#14B8A6",
    badge: "Brooklyn NYC",
    year: "2026",
    tags: ["Private Gym", "Brooklyn NYC", "Personal Training", "Community"],
    description: "Warm, community-driven fitness studio website built for a private Brooklyn neighborhood gym featuring family plans, group class schedules, and trainer bios.",
    highlights: ["Interactive class schedule calendar", "Membership pass signup", "Community story spotlights"]
  },
  {
    id: "hydro-healing",
    title: "Hydro Healing Cardiff",
    tagline: "Hydrotherapy, Infrared Recovery & Holistic Spa Wellness",
    category: "fitness",
    categoryLabel: "Fitness & Wellness",
    url: "https://hydro-healing.netlify.app/",
    accent: "#0EA5E9",
    badge: "Cardiff Spa",
    year: "2026",
    tags: ["Hydrotherapy", "Cardiff UK", "Holistic Wellness", "Spa Recovery"],
    description: "Tranquil wellness and hydrotherapy clinic website delivering serene aesthetics, treatment ritual descriptions, sensory deprivation suite tours, and booking.",
    highlights: ["Sensory spa visual ambience", "Treatment journey breakdowns", "Direct consultation reservation"]
  },
  {
    id: "strata-vision",
    title: "STRATA",
    tagline: "The $1M Vision — Architectural Masterworks & Residences",
    category: "architecture",
    categoryLabel: "Architecture & Design",
    url: "https://zesty-biscochitos-d6642c.netlify.app/",
    accent: "#A855F7",
    badge: "$1M Vision",
    year: "2026",
    tags: ["Architecture", "Ultra-Luxury Real Estate", "Bespoke Villas"],
    description: "A breathtaking architectural design portfolio highlighting monumental cantilevered residential villas, sustainable monolithic concrete structures, and private estates.",
    highlights: ["Ultra-minimalist editorial layouts", "Bespoke floorplan blueprints", "Cinematic scale photography"]
  },
  {
    id: "oblivion-structures",
    title: "OBLIVION STRUCTURES",
    tagline: "Futuristic Mega-Structures & Next-Era Engineering",
    category: "architecture",
    categoryLabel: "Architecture & Design",
    url: "https://dynamic-cannoli-50cea5.netlify.app/",
    accent: "#F43F5E",
    badge: "Structural Demo",
    year: "2026",
    tags: ["Mega-structures", "Engineering", "Futuristic Design", "Sci-Fi Arch"],
    description: "Avant-garde structural architecture and experimental engineering showcase exploring brutalist geometric forms, carbon-negative towers, and skyline monuments.",
    highlights: ["Sci-Fi architectural concepting", "Dynamic 3D structural previews", "Experimental typography system"]
  },
  {
    id: "serenity-studio",
    title: "Serenity Design Studio",
    tagline: "The Flagship Experience — Minimalist Interior Architecture",
    category: "architecture",
    categoryLabel: "Architecture & Design",
    url: "https://serenity-studio-demo.netlify.app/",
    accent: "#84CC16",
    badge: "Flagship Studio",
    year: "2026",
    tags: ["Interior Architecture", "Minimalism", "Scandinavian Living", "Lighting"],
    description: "Calm, harmonious interior design studio portal celebrating natural materials, bespoke lighting installations, Japandi principles, and tailored residential spaces.",
    highlights: ["Spatial lighting demonstrations", "Material swatch palette guide", "Bespoke interior project case studies"]
  },
  {
    id: "furniro-hackathon",
    title: "Furniro",
    tagline: "Contemporary Furniture & Interior Living E-Commerce",
    category: "ecommerce",
    categoryLabel: "E-Commerce",
    url: "https://talha-next-hackathon.vercel.app/",
    accent: "#EAB308",
    badge: "Next.js Hackathon",
    year: "2026",
    tags: ["Next.js", "Hackathon", "E-Commerce", "Furniture Store"],
    description: "Full-stack modern e-commerce storefront crafted for contemporary furniture enthusiasts with product filtering, category carousels, responsive cart, and checkout flow.",
    highlights: ["Next.js App Router performance", "Rich product detail previews", "Full e-commerce shopping experience"]
  }
];

// Group categories with counts
const CATEGORIES = [
  { id: "all", label: "All Projects" },
  { id: "automotive", label: "Automotive & Detailing" },
  { id: "luxury", label: "Luxury & Jewelry" },
  { id: "fitness", label: "Fitness & Wellness" },
  { id: "architecture", label: "Architecture & Design" },
  { id: "ecommerce", label: "E-Commerce" }
];
